version: '3.8'

services:
  web:
    build: .
    container_name: mtg-inventory-manager
    ports:
      - "5000:5000"
    volumes:
      - ./src/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped